version: "3.9"

services:
  db:
    container_name: crm_db
    image: postgres:14.0
    restart: always
    ports:
      - 5432:5432
    env_file:
      - api/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend-network

  redis:
    container_name: crm_redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    env_file:
      - api/.env
    volumes:
      - redis:/var/lib/redis
    networks:
      - backend-network

  api:
    container_name: crm_api
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - api/.env
    depends_on:
      - db
    networks:
      - backend-network

networks:
  backend-network:

volumes:
  postgres:
  redis:
